# Generated by Django 3.2.18 on 2024-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("thumbnail", models.URLField()),
                ("description", models.TextField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
