# Generated by Django 3.2.18 on 2024-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0002_scrapedvideo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videosummary",
            old_name="url",
            new_name="video_url",
        ),
        migrations.RemoveField(
            model_name="videosummary",
            name="title",
        ),
        migrations.AddField(
            model_name="videosummary",
            name="video_title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="query",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="videosummary",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
