# Generated by Django 3.2.18 on 2024-08-29 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("summarizer", "0003_auto_20240829_1752"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapedvideo",
            name="description",
        ),
        migrations.AddField(
            model_name="scrapedvideo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scrapedvideo",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
