# Generated by Django 3.2.18 on 2024-09-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0006_videosummary_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="videosummary",
            name="short_description",
            field=models.TextField(default="No short description available."),
        ),
    ]
